In [9]:
import numpy as np

In [18]:
a = np.random.randint(10,50, size=(5,2,3), dtype="int8")

In [19]:
a.shape

(5, 2, 3)

In [20]:
a.ndim

3

In [21]:
a.dtype

dtype('int8')

In [22]:
a.size

30

In [23]:

a.T

array([[[45, 20, 41, 11, 48],
        [38, 33, 36, 15, 21]],

       [[41, 47, 36, 43, 48],
        [17, 35, 15, 27, 46]],

       [[29, 44, 29, 29, 22],
        [33, 22, 23, 14, 30]]], dtype=int8)

In [24]:
a.shape

(5, 2, 3)

In [26]:
a.reshape(3,5,2)

array([[[45, 41],
        [29, 38],
        [17, 33],
        [20, 47],
        [44, 33]],

       [[35, 22],
        [41, 36],
        [29, 36],
        [15, 23],
        [11, 43]],

       [[29, 15],
        [27, 14],
        [48, 48],
        [22, 21],
        [46, 30]]], dtype=int8)

In [31]:
a.reshape(3,-1,1)

array([[[45],
        [41],
        [29],
        [38],
        [17],
        [33],
        [20],
        [47],
        [44],
        [33]],

       [[35],
        [22],
        [41],
        [36],
        [29],
        [36],
        [15],
        [23],
        [11],
        [43]],

       [[29],
        [15],
        [27],
        [14],
        [48],
        [48],
        [22],
        [21],
        [46],
        [30]]], dtype=int8)

In [32]:
a.ravel()

array([45, 41, 29, 38, 17, 33, 20, 47, 44, 33, 35, 22, 41, 36, 29, 36, 15,
       23, 11, 43, 29, 15, 27, 14, 48, 48, 22, 21, 46, 30], dtype=int8)

In [53]:
b = np.random.randint(1,10,(2,3))
c = np.random.randint(1,10,(2,3))
b,c

(array([[8, 8, 5],
        [2, 3, 6]], dtype=int32),
 array([[2, 3, 3],
        [2, 3, 7]], dtype=int32))

In [54]:
d = np.concatenate([b,c],axis=0)
d

array([[8, 8, 5],
       [2, 3, 6],
       [2, 3, 3],
       [2, 3, 7]], dtype=int32)

In [55]:
np.vstack((b,c))

array([[8, 8, 5],
       [2, 3, 6],
       [2, 3, 3],
       [2, 3, 7]], dtype=int32)

In [56]:
np.hstack((b,c))

array([[8, 8, 5, 2, 3, 3],
       [2, 3, 6, 2, 3, 7]], dtype=int32)

In [62]:
np.split(d,3,axis=1)

[array([[8],
        [2],
        [2],
        [2]], dtype=int32),
 array([[8],
        [3],
        [3],
        [3]], dtype=int32),
 array([[5],
        [6],
        [3],
        [7]], dtype=int32)]