## 1. Elementwise Operations

In [2]:
import numpy as np

In [3]:
a = np.array([[4,5,6],[5,6,7]])
b = np.array([[3,2,1],[9,8,1]])

In [4]:
a,b

(array([[4, 5, 6],
        [5, 6, 7]]),
 array([[3, 2, 1],
        [9, 8, 1]]))

## 

## Arithmetic operation

In [5]:
#a+b
np.add(a,b)

array([[ 7,  7,  7],
       [14, 14,  8]])

In [6]:
#a-b
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -2,  6]])

In [7]:
#a * b
np.multiply(a,b)

array([[12, 10,  6],
       [45, 48,  7]])

In [8]:
# a**2
#np.square(a)
np.pow(a,2)

array([[16, 25, 36],
       [25, 36, 49]])

In [9]:
#a % b
quo, rem =np.divmod(a,b)

In [10]:
rem

array([[1, 1, 0],
       [5, 6, 0]])

## Trignometric

In [11]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

In [12]:
new=1 / np.tan(b)
new

array([[-7.01525255, -0.45765755,  0.64209262],
       [-2.21084541, -0.14706506,  0.64209262]])

## Rounding operatons

In [13]:
np.around(new, decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

In [14]:
np.fix(new)

array([[-7., -0.,  0.],
       [-2., -0.,  0.]])

In [15]:
np.ceil(new)

array([[-7., -0.,  1.],
       [-2., -0.,  1.]])

## 2. Matrix operation

In [16]:
a = np.array([[4,5,6],[1,2,3]])
b = np.random.randint(1,10,(3,3))

In [17]:
a,b

(array([[4, 5, 6],
        [1, 2, 3]]),
 array([[3, 7, 3],
        [6, 9, 7],
        [2, 5, 9]], dtype=int32))

In [18]:
np.dot(a,b)

array([[ 54, 103, 101],
       [ 21,  40,  44]])

In [19]:
np.dot(b,a.T)

array([[ 65,  26],
       [111,  45],
       [ 87,  39]])

In [20]:
#a.T
np.transpose(a)

array([[4, 1],
       [5, 2],
       [6, 3]])

In [21]:
np.trace(b)

np.int64(21)

In [22]:
#Inverse of array

In [23]:
np.linalg.det(b)

np.float64(-105.99999999999997)

In [24]:
np.linalg.inv(b)

array([[-0.43396226,  0.45283019, -0.20754717],
       [ 0.37735849, -0.19811321,  0.02830189],
       [-0.11320755,  0.00943396,  0.14150943]])

In [25]:
np.dot(
    b, np.linalg.inv(b)
).round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

Solve equations
x + 2y = 1 , 3x + 5y = 2

In [26]:
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

In [27]:
x = np.linalg.solve(a,b)

In [28]:
x

array([-1.,  1.])

In [29]:
np.dot(a,x)

array([1., 2.])

## Array Broadcasting

In [34]:
a * 4

array([[ 4,  8],
       [12, 20]])