In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.6'

## Creating Numpy Arrray

In [4]:
list1 = [[2,3,4]]

In [5]:
arr1 = np.array(list1)

In [6]:
arr1

array([[2, 3, 4]])

In [7]:
arr1.shape

(1, 3)

In [8]:
arr1.ndim

2

In [9]:
list1 = [[2,3,4],
        [3,4,5],
         [5,6,7]]
arr2 = np.array(list1)

In [10]:
arr2

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [11]:
arr2.shape

(3, 3)

In [12]:
arr2.ndim

2

In [13]:
np.zeros(shape=(4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:


np.ones(shape=(2,3,3), dtype="int8")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [15]:
np.full(shape=(3,4),fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [16]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [17]:
np.linspace((0,1,2),(10,20,30), num=20)

array([[ 0.        ,  1.        ,  2.        ],
       [ 0.52631579,  2.        ,  3.47368421],
       [ 1.05263158,  3.        ,  4.94736842],
       [ 1.57894737,  4.        ,  6.42105263],
       [ 2.10526316,  5.        ,  7.89473684],
       [ 2.63157895,  6.        ,  9.36842105],
       [ 3.15789474,  7.        , 10.84210526],
       [ 3.68421053,  8.        , 12.31578947],
       [ 4.21052632,  9.        , 13.78947368],
       [ 4.73684211, 10.        , 15.26315789],
       [ 5.26315789, 11.        , 16.73684211],
       [ 5.78947368, 12.        , 18.21052632],
       [ 6.31578947, 13.        , 19.68421053],
       [ 6.84210526, 14.        , 21.15789474],
       [ 7.36842105, 15.        , 22.63157895],
       [ 7.89473684, 16.        , 24.10526316],
       [ 8.42105263, 17.        , 25.57894737],
       [ 8.94736842, 18.        , 27.05263158],
       [ 9.47368421, 19.        , 28.52631579],
       [10.        , 20.        , 30.        ]])

In [18]:
np.random.randint(0,10, size=(2,2))

array([[5, 1],
       [4, 8]], dtype=int32)

In [19]:
np.ones(shape = (2,2,1,3), dtype="int8")

array([[[[1, 1, 1]],

        [[1, 1, 1]]],


       [[[1, 1, 1]],

        [[1, 1, 1]]]], dtype=int8)

## Accesing an Array

In [20]:
a = np.array([1,2,3,4,5])

In [21]:
a[3]

np.int64(4)

In [22]:
a[0:4:2]

array([1, 3])

In [23]:
#2D
b = np.random.randint(0,25, size = (3,3))

In [24]:
b

array([[ 1,  9, 12],
       [18, 20,  4],
       [21, 24, 24]], dtype=int32)

In [25]:
b[1,0]

np.int32(18)

In [26]:
b[-1,0]

np.int32(21)

In [27]:
#slicing 2D array
b[:3,1]

array([ 9, 20, 24], dtype=int32)

In [28]:
b[:,2]

array([12,  4, 24], dtype=int32)

In [29]:
#3D
c = np.random.randint(0,25, size=(3,3,2))

In [30]:
c

array([[[ 6,  3],
        [22, 19],
        [ 2,  1]],

       [[ 3,  9],
        [21, 15],
        [10, 12]],

       [[19,  3],
        [ 8, 14],
        [17, 16]]], dtype=int32)

In [33]:
c[0,2,1]

np.int32(1)

In [34]:
c[:,2,:]

array([[ 2,  1],
       [10, 12],
       [17, 16]], dtype=int32)

In [35]:
dataset = np.random.randint(0,100,(1600,25))

In [37]:
dataset[:,0]

array([40, 88, 63, ..., 21, 70, 71], shape=(1600,), dtype=int32)

In [38]:
imagedataset = np.random.randint(0,100,(16,3,720,720))

In [42]:
imagedataset[1, 0, :, :]

array([[67, 62,  4, ..., 40, 95, 11],
       [71, 13,  3, ..., 48, 69, 36],
       [74, 31, 71, ..., 43, 79,  0],
       ...,
       [63, 12, 81, ..., 72, 64, 67],
       [98,  4, 38, ..., 63, 14, 34],
       [86,  2, 94, ..., 60, 46, 12]], shape=(720, 720), dtype=int32)

## Boolean or mask indexing

In [43]:
a = np.random.randint(1,7,(5,5))

In [44]:
a

array([[3, 1, 4, 1, 4],
       [2, 5, 5, 3, 1],
       [3, 3, 2, 4, 3],
       [6, 4, 6, 6, 3],
       [4, 2, 6, 3, 4]], dtype=int32)

In [45]:
mask = a > 5

In [46]:
mask

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False,  True,  True, False],
       [False, False,  True, False, False]])

In [47]:
a[mask]

array([6, 6, 6, 6], dtype=int32)

In [48]:
mask = [True, False, False, True, True]

In [49]:
a[mask]

array([[3, 1, 4, 1, 4],
       [6, 4, 6, 6, 3],
       [4, 2, 6, 3, 4]], dtype=int32)