## 1. Elementwise Operations

In [2]:
import numpy as np

In [14]:
a = np.array([[4,5,6],[5,6,7]])
b = np.array([[3,2,1],[9,8,1]])

In [15]:
a,b

(array([[4, 5, 6],
        [5, 6, 7]]),
 array([[3, 2, 1],
        [9, 8, 1]]))

## 

## Arithmetic operation

In [16]:
#a+b
np.add(a,b)

array([[ 7,  7,  7],
       [14, 14,  8]])

In [17]:
#a-b
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -2,  6]])

In [18]:
#a * b
np.multiply(a,b)

array([[12, 10,  6],
       [45, 48,  7]])

In [19]:
# a**2
#np.square(a)
np.pow(a,2)

array([[16, 25, 36],
       [25, 36, 49]])

In [21]:
#a % b
quo, rem =np.divmod(a,b)

In [22]:
rem

array([[1, 1, 0],
       [5, 6, 0]])

## Trignometric

In [23]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

In [26]:
new=1 / np.tan(b)
new

array([[-7.01525255, -0.45765755,  0.64209262],
       [-2.21084541, -0.14706506,  0.64209262]])

## Rounding operatons

In [27]:
np.around(new, decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

In [28]:
np.fix(new)

array([[-7., -0.,  0.],
       [-2., -0.,  0.]])

In [29]:
np.ceil(new)

array([[-7., -0.,  1.],
       [-2., -0.,  1.]])